# Generated by Django 4.2.3 on 2023-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tim_minutes',
            new_name='time_minutes',
        ),
    ]
