# Generated by Django 4.2.3 on 2023-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_recipe_created_at_recipe_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='recipe updated at'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
